### ISSUE TITLE
Helm chart values has missing carriage return

### ISSUE THREAD

**Issue by mikhailadvani** [cloudability/metrics-agent#145]
The values file should look like
```
drop:
- all
```

and not 
```
drop: - all
```
With the current setup we get the error `Error: cannot load values.yaml: error converting YAML to JSON: yaml: line 65: block sequence entries are not allowed in this context`

**Comment by cadams8238** [comment]
Hi @mikhailadvani - thanks for raising this issue with our team. We have deployed a fix for this bug in this release: https://github.com/cloudability/metrics-agent/releases/tag/v2.4
