### ISSUE TITLE
Publish Helm Chart

### ISSUE THREAD

**Issue by alex0ptr** [cloudability/metrics-agent#168]
[As mentioned before](https://github.com/cloudability/metrics-agent/issues/70#issuecomment-607883678) the repository contains sources for an Helm Chart but it is not independently versioned nor published to a chart registry.

In our project we are using https://github.com/renovatebot/renovate to be notified by changes to external Helm dependencies in our GitOps repository. The only chart we are using that is not supporting this workflow and therefore is harder to maintain is the metrics-agent.

Please consider using [chart releaser](https://helm.sh/docs/howto/chart_releaser_action/) or similar to conform with Helm standard packaging.

**Comment by daniel-spray** [comment]
Public helm chart support now available.

**Comment by alex0ptr** [comment]
Nice! Thank you!

**Comment by omichels** [comment]
great work!
