### ISSUE TITLE
Please align helm chart releases to image releases and remove :latest image tag

### ISSUE THREAD

**Issue by technotaff-nbs** [cloudability/metrics-agent#178]
It is best practice to align a helm-chart release to an image release.

This way a helm chart upgrade results in an image upgrade on next release, rather than having a floating and non-specific result.

Please fix the image tag in your helm chart releases to a specific release.

**Comment by daniel-spray** [comment]
Hi! 
Sorry for the delayed response on this Issue request. I was wondering what exactly you are looking for by this request. Do you want us to update our version and appVersion in Chart.yaml to match the release version. 
For example our current metrics-agent release is v2.8 and you want us to update the helm chart version to 2.8 as well?

My confusion in doing that is in the Chart.yaml it suggests the version should only be incremented if changes are made to the chart. We have releases where changes are only made to the application which would cause that versioning to be out of sync in the future.
Thanks!

**Comment by technotaff-nbs** [comment]
Thanks for implementing this.
