### ISSUE TITLE
Please move to semantic versioning on next release of image/chart

### ISSUE THREAD

**Issue by technotaff-nbs** [cloudability/metrics-agent#188]
Hello team,

Thank you for the recent work to move to fixed image-versions in the recent release.

Could we please also ensure that the helm chart move to helm-standard [semantic versioning](https://helm.sh/docs/chart_best_practices/conventions/#version-numbers)?

We use some automation tools to import helm charts, security-assess them and stage into our internal repositories but these tools do not like non-semantic versioning. Could the next chart release be something like 2.10.0?

**Comment by daniel-spray** [comment]
Should be fixed in with the newest release: https://github.com/cloudability/metrics-agent/releases/tag/v2.10.0

**Comment by technotaff-nbs** [comment]
Thank you!
