### ISSUE TITLE
Deprecation of Heapster

### ISSUE THREAD

**Issue by daviddyball** [cloudability/metrics-agent#19]
Heapster has been deprecated in favour of the Kubernetes `metrics-server` and Custom Metrics API (see this commit:
https://github.com/kubernetes/heapster/commit/801cea9231639211e9cacffc7498a19ab6b01cd2).

Metrics Agent should look to moving over to `metrics-server` as soon as possible.

**Comment by housejester** [comment]
Yep, thanks! We are aware of its deprecation and 1.13 retirement. It is high on our list (basically the next active thing to tackle). The agent will still need to support heapster for older clusters, and will continue to fire up its own heapster in those environments if not present, but we will have a different metrics source for later versions.

**Comment by andrepoleza** [comment]
@housejester do we have a timeline expectation for `metrics-server` support? Is this going to happen in the next 1~3 months?

**Comment by DavidXArnold** [comment]
@andrepoleza We expect to have the requirement for Heapster removed within the next 1-2 months.

**Comment by DavidXArnold** [comment]
Heapster is no longer a requirement for the metrics-agent. It now will pull metrics from the Kubernetes API and directly from each node in the cluster it is running in.

**Comment by gregsidelinger** [comment]
Is this fix released yet? I see 1.0.1 was released a few days back and I'm wondering if this in it.

**Comment by caseydoran** [comment]
Yes, this release includes removal of the reliance on Heapster. Thanks.

**Comment by marcstreeter** [comment]
is the `kubectl top <resource>` command also deprecated as it depended on heapster?

**Comment by DavidXArnold** [comment]
It is not , it just now requires that you run either heapster or the [metrics-server](https://github.com/kubernetes-incubator/metrics-server) in your cluster
