### ISSUE TITLE
Support AKS 1.24

### ISSUE THREAD

**Issue by MattGarner-N** [cloudability/metrics-agent#198]
AKS 1.24 is GA, please can this be officially supported?

https://azure.microsoft.com/en-us/updates/generally-available-kubernetes-124-support/

**Comment by patrick-guy-rodies** [comment]
Any feedback on this one will be great. We are going to upgrade the whole fleet of clusters to 1.24. It means that we will not have the agent running.

**Comment by daniel-spray** [comment]
We will be targeting next week for this support, thanks.

**Comment by patrick-guy-rodies** [comment]
Any update on this one guys? thanks

**Comment by daniel-spray** [comment]
AKS 1.24 is now officially supported

**Comment by patrick-guy-rodies** [comment]
Great work guys thanks
