### ISSUE TITLE
Track energy consumption

### ISSUE THREAD

**Issue by wielrenner** [cloudability/metrics-agent#237]
We would like to add energy consumption to our KPIs besides costs. 
An idea is to use Kepler https://github.com/sustainable-computing-io/kepler. 
Would it be possible to integrate Kepler or sort like metrics into the metrics agents, so we can track the energy consumption from within Cloudability?

**Comment by daniel-spray** [comment]
Hi @wielrenner 
Thanks for reaching out and suggesting this addition to the metrics-agent and Cloudability.

We do not currently handle feature requests through this repository so please submit this feature request through your Apptio account.
