### ISSUE TITLE
Helm - Ability to pass extraObjects

### ISSUE THREAD

**Issue by patpicos** [cloudability/metrics-agent#266]
When deploying the metrics-agent, we would like to deploy resources such as `SecretStore` and `ExternalSecret` to allow the cloudability api key to be sourced externally and use the `secretName` attribute.

Note: I will be submitting a PR for this.

**Comment by daniel-spray** [comment]
Hi @patpicos 
Thank you for your contribution! 
We have added this support in the 2.11.30 release! 
https://github.com/cloudability/metrics-agent/releases/tag/metrics-agent-2.11.30
