### ISSUE TITLE
Truncated node summary files.

### ISSUE THREAD

**Issue by mnorbury** [cloudability/metrics-agent#42]
Node summary files are at risk of being truncated since the underlying file handler is not closed. File handlers that aren't explicitly closed are eventually closed at GC time. However, since a close call also flushed the output to disk, there is a risk that the node summary files are tar'd up before all the data is written to disk.

This issue is to refactor the code to close file handlers when the data has been fully written.

**Comment by DavidXArnold** [comment]
fixed by #43
