### ISSUE TITLE
All the logs generated by the metrics-agent seem to be written to stderr

### ISSUE THREAD

**Issue by JonathanLachapelle** [cloudability/metrics-agent#48]
I'm testing the metrics-agent on a GKE cluster and all the logs are reported as severity : ERROR.

It's a bit confusing because when you see an error log like this : "2019/09/13 19:41:10 Uploading Metrics", you might think the metric agent is not working when it's actually working.

Since it takes up to 48 hours to know if the metrics are reaching cloudability, it's important to have the right severity for the logs. 

From what I can see, 100% of the logs are written to STDERR

**Comment by JonathanLachapelle** [comment]
I have looked a bit at the code and the issue is that you are using log from go which default to stderr.

So when you write a line like this in kubernetes.go line 121 : log.Printf("Cloudability Metrics Agent successfully started."), the end-user will see in its log ERROR : Cloudability Metrics Agent successfully started.

This type of behavior is quite confusing and if we want to monitor the health of the container, it's a bit difficult to determine if it's a real issue or not.

**Comment by DavidXArnold** [comment]
@JonathanLachapelle Thank you for raising this issue. We have had a couple of requests to improve the logging facilities of the metrics-agent.  I have created issue #49 which encompasses this and others requests around improving the agents' logging facilities.
