### ISSUE TITLE
healtcheck

### ISSUE THREAD

**Issue by nullck** [cloudability/metrics-agent#52]
Hello,

I'd like to purpose a health-check parameter where is possible to check if the agent can connect throw the Cloudability Api in order to check the API KEY or other configurations parameters are correct or not.

Today I can't check if my configurations are correct or not since the logs don't give any clue to me.

```
kubectl logs cloudability-agent-7fc4b55dd9-hljq5 -n monitoring [9:59:27]
time="2019-09-30T12:54:40Z" level=debug msg="Log level set to: debug"
time="2019-09-30T12:54:40Z" level=info msg="Starting Cloudability Kubernetes Metric Agent version: 1.0.11"
time="2019-09-30T12:54:40Z" level=info msg="Primary metrics collected directly from each node."
time="2019-09-30T12:54:41Z" level=info msg="Cloudability Metrics Agent successfully started."
```

Looking there my data should be available in the dashboard, but this is not working, I can't see my Kubernetes usage data in the dashboard.

**Comment by daniel-spray** [comment]
With this release https://github.com/cloudability/metrics-agent/releases/tag/metrics-agent-2.11.5 the agent will perform a "Connectivity Check" on startup which will log if it can not retrieve the presigned s3 url.
