### ISSUE TITLE
Non-numeric user (agent) Error

### ISSUE THREAD

**Issue by webbdog28** [cloudability/metrics-agent#82]
This is the error I'm getting when trying to run the metrics-agent in Kubernetes 1.15.10:

"Error: container has runAsNonRoot and image has non-numeric user (agent), cannot verify user is non-root"

This was fixed by changing the deployment.yaml file and adding the following:

      securityContext: 
        runAsUser: 1000

I would suggest either adding that to the deployment.yaml or updating the Dockerfile.

**Comment by johnjeffers** [comment]
https://github.com/cloudability/metrics-agent/pull/84

**Comment by johnjeffers** [comment]
Reopening, realized the Helm chart fix does not address this.

**Comment by paulbhart** [comment]
The better solution is the one I listed here https://github.com/cloudability/metrics-agent/issues/85.  It doesn't change functionality just ensure the USER command in the docker file is a numeric id vs. a alpha value.

**Comment by mnorbury** [comment]
This should be fixed by #87, closing the issue. Please re-open if this continues to be a problem.
